{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: go-app-ingress
  namespace: {{ .Values.namespace }}
  labels:
    app: go-app
  annotations:
{{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
{{- end }}
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.path }}
        pathType: {{ .Values.ingress.pathType }}
        backend:
          service:
            name: go-app-service
            port:
              number: {{ .Values.service.port }}
{{- end }}
