{{- if and .Values.logging.enabled .Values.logging.persistentVolume.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: go-app-logs-pvc
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: {{ .Values.logging.persistentVolume.storageClass }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.logging.persistentVolume.size }}
{{- end }}
